version: '3'

services:
  backend:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - ENVIRONMENT=development
      - OPENAI_API_KEY=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
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    command: >
      bash -c "python -m app.init_db && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    command: npm run dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 